language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t yashbrahmb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yashbrahmb/docker-react npm run test